version: '3'
volumes:
#  web-admin:
  absol-admin:
services:
  nginx:
    image: nginx
    restart: always
    hostname: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d/
      - ./data/files:/opt/resources/
      - absol-admin:/opt/absol-admin
    ports:
      - "41000:80"
  redis:
    image: redis
    restart: always
    ports:
      - "46379:6379"
    hostname: redis
    command: redis-server --requirepass $REDIS_PASSWD
    volumes:
      - ./data/redis:/data
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    ports:
      - "45432:5432"
    environment:
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
