server:
  port: 3000
  servlet:
    context-path: /api/bul
spring:
  jackson:
    default-property-inclusion: use_defaults
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  application:
    name: bul-backend
logging:
  level:
    root: info
  file:
    name: ${LOGPATH:./logs/${spring.application.name}.api.log}
