name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          servers: '[{ "id": "releases", "username": "admin", "password": "wuchuan@" }, { "id": "snapshots", "username": "admin", "password": "wuchuan@" }]'
          mirrors: '[{ "id": "nexus", "mirrorOf": "*", "url": "https://nexus.wuchuangroup.com/repository/maven-public/" }]'
      - name: Cat setting.xml
        run: cat /home/runner/.m2/settings.xml
      - name: Build backend with Maven
        run: mvn -B package --file backend/pom.xml
      - name: Build the Docker image
        run: docker build . --file backend/Dockerfile --tag break_up_ledger_backend:latest
